# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f76d4bb046576594d4321ebe63806af94b05b5b6e002a1755a700cd9515b5bf03ebb0651b676d7858c78d230fbb0cc12d827ea5a0747c931e3233ee7b5b53ec3

test:
  secret_key_base: b01cde88ec8a83043ba1aaf0b6f1480d36f82e9a2555b29238816e29c1281e21234616ecda63be67b6f14f15a8e1d40acf9abe2d6ada0ae18b911ed87929bb48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
